#!/bin/bash

# Purprose:
# Completely reinstall Virtuozzo Automator Agent
# and clean up all required folders.

yum -y remove va-agent-* va-pp-* rdbmspp-debuginfo sqlite3odbc-debuginfo

rm -rf /var/opt/pva
rm -rf /var/log/pva
rm -rf /opt/pva

yum clean all
yum install -y va-agent-* va-pp-* rdbmspp-debuginfo sqlite3odbc-debuginfo

# Increase verbosity
/opt/pva/agent/bin/vzlxmlman -s 6 -i data/system/configuration/log_level /var/opt/pva/agent/etc/vzagent.conf

for i in va-agent httpd; do
    systemctl start ${i}

    if [ ${PIPESTATUS[0]} != 0 ]; then
        echo "Failed to start ${i} service"
        exit 1
    fi
done

